package main

import (
	"fmt"
	"sort"
)

// TODO
// This should be a query which accepts a market, it's incovation in the context of trade_routes should pass the relavent market
func HowManyTradeGoodCanIAfford(agent Agent, trade_good TradeGood) int64 {
	fmt.Println("[DEBUG] HowManyTradeGoodCanIAfford")
	fmt.Print("[DEBUG] agent.Credits = ")
	fmt.Print(agent.Credits)
	fmt.Println()
	fmt.Print("[DEBUG] trade_good.PurchasePrice = ")
	fmt.Print(trade_good.PurchasePrice)
	fmt.Println()
	max_buy_count := agent.Credits / trade_good.PurchasePrice
	return max_buy_count
}

// calculate credits/second generated by running this trade route
func PrintTradeRoutes() {
	for _, trade_route := range trade_routes {
		fmt.Print("[INFO] BUY ")

		fmt.Printf("%-15v", trade_route.TradeGoodSymbol)

		fmt.Print(" AT ")
		fmt.Printf("%-10v", trade_route.BuyMarketplaceWaypointSymbol)
		fmt.Print(" FOR ")
		fmt.Printf("%-5v", trade_route.BuyMarketTradeGood.PurchasePrice)
		fmt.Print(" SELL AT ")
		fmt.Printf("%-15v", trade_route.SellMarketplaceWaypointSymbol)
		fmt.Print(" FOR ")
		fmt.Printf("%-6v", trade_route.SellMarketTradeGood.SellPrice)
		fmt.Print(" PPU ")
		fmt.Printf("%-5v", trade_route.ProfitPerUnit)
		fmt.Print(" DISTANCE ")
		fmt.Printf("%-5v", trade_route.Distance)
		fmt.Print(" SCORE ")
		fmt.Printf("%.2f", trade_route.ProfitabilityRating)
		fmt.Println()
	}
}

func CalculateProfitPerUnit(trade_route TradeRoute) float64 {
	//fmt.Println("[DEBUG] CalculateProfitPerUnit")
	if trade_route.BuyMarketTradeGood.PurchasePrice == 0 {
		fmt.Println("[WARNING] CalculateProfitPerUnit trade_route.BuyMarketTradeGood.PurchasePrice == 0")
        return 0
	}
	if trade_route.SellMarketTradeGood.SellPrice == 0 {
		fmt.Println("[WARNING] CalculateProfitPerUnit trade_route.SellMarketTradeGoodPurchasePrice == 0")
		return 0
	}
	sell_price := float64(trade_route.SellMarketTradeGood.SellPrice)
	buy_price := float64(trade_route.BuyMarketTradeGood.PurchasePrice)
	profit_per_unit := sell_price - buy_price
	return profit_per_unit
}

func PopulateTradeRoutesProfitPerUnit() {
	fmt.Println("[DEBUG] PopulateTradeRoutesProfitPerUnit")
	for i, trade_route := range trade_routes {
		if trade_route.BuyMarketTradeGood.PurchasePrice == 0 || trade_route.SellMarketTradeGood.SellPrice == 0 {
			fmt.Println("[WARN] Trade route lacks price data, skipping.")
			continue
		}
		profit_per_unit := CalculateProfitPerUnit(trade_route)
		trade_routes[i].ProfitPerUnit = int64(profit_per_unit)
		if trade_route.Distance == 0 {
			trade_route.Distance = 1
		}
		profit_per_unit_divide_by_distance_times_two := profit_per_unit / float64(trade_route.Distance*2)
		fmt.Println(profit_per_unit_divide_by_distance_times_two)
		trade_routes[i].ProfitabilityRating = profit_per_unit_divide_by_distance_times_two
	}
}

func MostProfitableTradeRoute(trade_routes []TradeRoute) TradeRoute {
	//println("[DEBUG] MostProfitableTradeRoute")
	//println("[DEBUG] len(trade_routes)")
	//println(len(trade_routes))

	most_profitable_trade_route := TradeRoute{}
	best_profitability_score := -9.00
	for _, trade_route := range trade_routes {
		//fmt.Printf("%.2f", trade_route.ProfitabilityRating)
		if trade_route.ProfitabilityRating > best_profitability_score {
			most_profitable_trade_route = trade_route
			best_profitability_score = trade_route.ProfitabilityRating
		}
	}

	return most_profitable_trade_route
}

func ShortestTradeRoute(trade_routes []TradeRoute) TradeRoute {
	shortest_trade_route := TradeRoute{}
	best_distance := 9999
	for _, trade_route := range trade_routes {
		if trade_route.Distance < best_distance {
			shortest_trade_route = trade_route
			best_distance = trade_route.Distance
		}
	}
	return shortest_trade_route
}

func TradeRoutesWithTradeGood(trade_routes []TradeRoute, trade_good_symbol string) []TradeRoute {
	var trade_routes_with_trade_good = []TradeRoute{}
	for _, trade_route := range trade_routes {
		if trade_route.TradeGoodSymbol == trade_good_symbol {
			trade_routes_with_trade_good = append(trade_routes_with_trade_good, trade_route)
		}
	}
	return trade_routes_with_trade_good
}

func UpdateTradeRoutesIncludingThisWaypoint(waypoint_symbol string) {
	market := GetMarket(base_system_symbol, waypoint_symbol)
	for i, trade_route := range trade_routes {
		if waypoint_symbol == trade_route.BuyWaypoint.Symbol {
			for _, trade_good := range market.TradeGoods {
				if trade_route.TradeGoodSymbol == trade_good.Symbol {
					trade_routes[i].BuyMarketTradeGood = trade_good
				}
			}
		}

		if waypoint_symbol == trade_route.SellWaypoint.Symbol {
			for _, trade_good := range market.TradeGoods {
				if trade_route.TradeGoodSymbol == trade_good.Symbol {
					trade_routes[i].SellMarketTradeGood = trade_good
				}
			}
		}
	}
	PopulateTradeRoutesProfitPerUnit()
	WriteTradeRoutesToFile(trade_routes, callsign)
}

func SatelliteToMarketAssignmentComplete(markets_to_cover map[string]string) bool {
	for _, v := range markets_to_cover {

		if len(v) == 0 {
			//fmt.Println("[DEBUG] SatelliteToMarketAssignment Incomplete")
			return false
		}
	}
	//fmt.Println("[DEBUG] SatelliteToMarketAssignment Complete")
	return true
}

func MarketScanComplete(trade_routes []TradeRoute) bool {

	if len(trade_routes) == 0 {
		fmt.Println("[WARN] NO TRADE ROUTES")
		return false
	}

	for _, trade_route := range trade_routes {
		if trade_route.BuyMarketTradeGood.PurchasePrice == 0 {
			fmt.Println("[INFO] Market data incomplete, wait for input...")
			return false
		}
	}
	fmt.Println("[INFO] Market data complete, let's trade...")
	return true
}

func PopulateTradeRoutesWithWaypointData(callsign string, trade_routes []TradeRoute, markets_to_cover map[string]string) {
	fmt.Println("[DEBUG] PopulateTradeRoutesWithWaypointData")
	all_waypoints_in_system := []Waypoint{}
	all_waypoints_in_system = ReadWaypointsFromFile(callsign)
	for market_waypoint := range markets_to_cover {
		get_waypoint_result := Waypoint{}
		for _, waypoint := range all_waypoints_in_system {
			if market_waypoint == waypoint.Symbol {
				get_waypoint_result = waypoint
			}
		}
		for i, trade_route := range trade_routes {
			if market_waypoint == trade_route.BuyMarketplaceWaypointSymbol {
				trade_routes[i].BuyWaypoint = get_waypoint_result
			}
			if market_waypoint == trade_route.SellMarketplaceWaypointSymbol {
				trade_routes[i].SellWaypoint = get_waypoint_result
			}
		}
	}
}

func PopulateTradeRoutesWithDistances(trade_routes []TradeRoute) {
	for i, trade_route := range trade_routes {
		distance := DistanceBetweenTwoWaypoints(trade_route.BuyWaypoint, trade_route.SellWaypoint)
		trade_routes[i].Distance = distance
	}
}

func RemoveTradeRoutesWithDistancesGreaterThanMaximumFuel(trade_routes []TradeRoute, maximum_fuel int64) {
	for i, trade_route := range trade_routes {
		if trade_route.Distance < int(maximum_fuel) {
			fmt.Println("[INFO] Removing trade route because distance is higher than fuel capacity")
			// remove trade route because it exceeds  maximum fuel
			trade_routes = append(trade_routes[:i], trade_routes[i+1:]...)
		}
	}
}

func IdentifyTradeRoutes(callsign string, markets_to_cover map[string]string, markets []Market, market_waypoints []Waypoint) []TradeRoute {
	fmt.Println("[DEBUG] IdentifyTradeRoutes")

	// cache for full response from every get_market call
	all_market_results := ReadMarketsFromFile(callsign)

	// return value container
	trade_routes := []TradeRoute{}

	// populate all_market results with the result of get_market against each waypoint which has a MARKETPLACE
	// listing waypoints by trait is broken.
	//marketplaces_in_system := ListWaypointInSystemByTrait(base_system_symbol, "MARKETPLACE")

	// populate both trade_routes and markets_to_cover by iterating through A) every MARKETPLACE B) each of their Imports and C) their Exports
	// associations of import/export are added to trade_routes, and we keep one copy of each waypoint_symbol in markets_to_cover
	for _, each_market_result := range all_market_results {
		if len(each_market_result.Exports) > 0 {
			for _, each_export := range each_market_result.Exports {
				for _, each_market_result_inner := range all_market_results {
					if len(each_market_result_inner.Imports) > 0 {
						for _, each_market_result_imports := range each_market_result_inner.Imports {
							if each_export.Symbol == each_market_result_imports.Symbol {
								trade_route := TradeRoute{}
								trade_route.TradeGoodSymbol = each_export.Symbol
								trade_route.BuyMarketplaceWaypointSymbol = each_market_result.Symbol
								trade_route.SellMarketplaceWaypointSymbol = each_market_result_inner.Symbol
								trade_routes = append(trade_routes, trade_route)
								markets_to_cover[trade_route.BuyMarketplaceWaypointSymbol] = ""
								markets_to_cover[trade_route.SellMarketplaceWaypointSymbol] = ""
							}
						}
					}
				}
			}
		}
	}

	PopulateTradeRoutesWithWaypointData(callsign, trade_routes, markets_to_cover)
	PopulateTradeRoutesWithDistances(trade_routes)
	return trade_routes
}

func PopulateMarketsToCover(trade_routes []TradeRoute) map[string]string {
	markets_to_cover := make(map[string]string)
	for _, trade_route := range trade_routes {
		markets_to_cover[trade_route.BuyMarketplaceWaypointSymbol] = ""
		markets_to_cover[trade_route.SellMarketplaceWaypointSymbol] = ""
	}
	return markets_to_cover
}

func AssignSatellitesToMarkets(markets_to_cover map[string]string) {

	fmt.Println("[DEBUG] AssignSatellitesToMarkets")
	list_of_ships := ListShips()
	list_of_satellites := []Ship{}

	for _, ship := range list_of_ships {
		if ship.Registration.Role == "SATELLITE" {
			list_of_satellites = append(list_of_satellites, ship)
		}
	}

	keys := make([]string, 0, len(markets_to_cover))

	for k := range markets_to_cover {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var market_index int
	for _, market_waypoint := range keys {
		// if this market does not have a satellite assigned:
		if markets_to_cover[market_waypoint] == "" {
			markets_to_cover[market_waypoint] = list_of_satellites[market_index].Symbol
			fmt.Println("[INFO] Assigned satellite " + list_of_satellites[market_index].Symbol + " to market " + market_waypoint)
		}
		market_index++
	}
}

func TradeRouteMissingData() (bool, TradeRoute) {
	empty_trade_route := TradeRoute{}
	for _, trade_route := range trade_routes {
		if trade_route.ProfitabilityRating == 0 {
			return true, trade_route
		}
	}
	return false, empty_trade_route
}